spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: InsideDayOffMarker
          uri: lb://InsideDayOffMarker
          predicates:
            - Path=/dayoffmarker/api/**,/dayoffmarker/swagger-ui/**,/dayoffmarker/v*/api-docs/**
