server:
  port: 9990

logging:
  exception-conversion-word:
  level:
    liquibase: INFO
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  cache:
    enable: true
    type: redis
    redis:
      key-prefix: 'api::'
      time-to-live: 12000000
  data:
    redis:
      repositories:
        enabled: false
      port: 26379
      password: '{cipher}ee350459afc884c66fe398edca0bdfcb9b6275c155af18beb3ecfd11c020da65e7add3f07145c42acbb4e83ea9e219f4'
      sentinel:
        database: 0
        master: InsideSoftwares
        nodes: localhost
        password: '{cipher}ee350459afc884c66fe398edca0bdfcb9b6275c155af18beb3ecfd11c020da65e7add3f07145c42acbb4e83ea9e219f4'
  
  datasource:
    url: jdbc:postgresql://localhost:5432/InsideSoftwares
    username: InsideSoftwaresAdmin
    password: '{cipher}8d0c375430ca0b826d83830c27749e779d3d380f34742f9c3aef54ce93d4df7a31475d70dfc4fca144bc58a66594a93e'
    hikari:
      connection-timeout: 5000
      idle-timeout: 150000
      max-lifetime: 300000
      minimum-idle: 10
      maximum-pool-size: 50
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
      names:
        - jobUpdateHoliday
        - jobCreatesDays
  task:
    scheduling:
      pool:
        size: 5

application:
  view_response_json: true
  scheduling:
    day:
      create_date:
        find_request_create_date: "0 */1 * * * *"
        run_request_create_date: "0 */3 * * * *"
        run_create_day_batch: "0 */1 * * * *"
        clear_day_batch: "0 0 */12 * * *"
    cache:
      clean: "0 0 */12 * * *"
    holiday:
      create:
        cron: "0 */1 * * * *"
      batch:
        create:
          cron: "0 */3 * * * *"
    tag:
      link:
        run_batch: "0 */10 * * * *"
      unlink:
        run_batch: "0 */10 * * * *"

dom:
  taskexecutor:
    corePoolSize: 500
    maxPoolSize: 1000
    queueCapacity: 1000
  job:
    chunk:
      requestToRunningUpdateHoliday: 2000
      requestsUpdateHoliday: 2000
      requestToFinalizedUpdateHoliday: 3000
      requestToRunningCreateDate: 2000
      requestsCreateDate: 2000
      requestToFinalizedCreateDate: 3000
      daysCreatedCreateDate: 3000
      dayBatchToProcessedCreateDate: 3000
      processDayBatch: 10000
      deleteAllDaysBatch: 10000

jdempotent:
  enable: false

insidesoftwares:
  filter:
    show-request-body: false
    show-request-headers: false
    show-response-body: false
