version: '3'

networks:
  dayoff_marker:
    driver: bridge

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: keycloak_dev
    hostname: keycloak_dev
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      [ "start-dev", "--http-port 7080", "--https-port 7443", "--import-realm" ]
    volumes:
      - ./keycloak:/opt/keycloak/data/import/
    ports:
      - 7080:7080
      - 7443:7443
    networks:
      - dayoff_marker